### ISSUE TITLE
dataset processing

### ISSUE THREAD

**Issue by heyabhiai** [kampta/DeepLayout#2]
Hi Kamal,

https://github.com/kampta/DeepLayout/blob/1e66e72c11a526b258fe3395fa4a0f23d29987a2/layout_transformer/dataset.py#L120-L130

In the JSONLayout class, bounding boxes are sorted but categories are not sorted.
Bounding boxes w.r.t categories are not matching as per PubLayNet json files after processing.
Can you please check it?

**Comment by kampta** [comment]
Hi @abhijeet00 , we don't sort the layout elements w.r.t the categories, but only by their position (followed by their size)

**Comment by kampta** [comment]
>Bounding boxes w.r.t categories are not matching as per PubLayNet json files after processing.

I am not sure what you mean by that. Can you clarify?

**Comment by heyabhiai** [comment]
Thank you for your response.

Each bounding box has an associated category label.
When bounding box array is sorted according to their position. The category array is not changed accordingly,
due to which mapping between the bounding box and class label changes, which further affects flattened sequence.

In case of any misunderstanding from my side, then please let me know. Thanks.

![Screenshot 2021-11-05 at 2 26 03 AM](https://user-images.githubusercontent.com/30382260/140420981-b958ebdb-d3c4-409b-af20-ccebbb207093.jpg)

**Comment by kampta** [comment]
Ahh that indeed is a bug. My apologies. I'll try to fix it shortly. PR welcome!

**Comment by kampta** [comment]
Resolved by #3
